name = "dino-cookies"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "galletas-db"
database_id = "18a3b2f3-6e95-47e6-8d00-c7b68ff0a13c"
